"""create territorial and user tables

Revision ID: 12e39403107c
Revises: 
Create Date: 2026-09-27 19:54:02.387096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e39403107c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distritos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('iglesias',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('distrito_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['distrito_id'], ['distritos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distrito_id', 'nombre', name='uq_iglesia_distrito_nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('distrito_id', sa.Uuid(), nullable=True),
    sa.Column('iglesia_id', sa.Uuid(), nullable=True),
    sa.Column('lider_id', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.Enum('ADMIN', 'PASTOR', 'LIDER', 'HERMANO', name='rol_usuario', native_enum=True, create_constraint=False), nullable=False),
    sa.Column('es_pastor_principal', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("es_pastor_principal = FALSE OR rol = 'PASTOR'", name='ck_usuario_pastor_principal_rol'),
    sa.CheckConstraint("rol <> 'HERMANO' OR (telefono IS NOT NULL AND direccion IS NOT NULL AND distrito_id IS NOT NULL AND iglesia_id IS NOT NULL AND lider_id IS NOT NULL)", name='ck_hermano_datos_requeridos'),
    sa.CheckConstraint("rol = 'HERMANO' OR (email IS NOT NULL AND password_hash IS NOT NULL)", name='ck_usuario_operativo_credenciales'),
    sa.CheckConstraint("rol IN ('ADMIN', 'PASTOR', 'LIDER', 'HERMANO')", name='ck_usuario_rol_valido'),
    sa.CheckConstraint("rol NOT IN ('PASTOR', 'LIDER') OR (distrito_id IS NOT NULL AND iglesia_id IS NOT NULL)", name='ck_usuario_operativo_asignacion'),
    sa.CheckConstraint('length(trim(apellido)) > 0', name='ck_usuario_apellido_no_vacio'),
    sa.CheckConstraint('length(trim(nombre)) > 0', name='ck_usuario_nombre_no_vacio'),
    sa.ForeignKeyConstraint(['distrito_id'], ['distritos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['iglesia_id'], ['iglesias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lider_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('uq_pastor_principal_por_iglesia', 'usuarios', ['iglesia_id'], unique=True, postgresql_where=sa.text("rol = 'PASTOR' AND es_pastor_principal = TRUE AND activo = TRUE"), sqlite_where=sa.text("rol = 'PASTOR' AND es_pastor_principal = 1 AND activo = 1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pastor_principal_por_iglesia', table_name='usuarios', postgresql_where=sa.text("rol = 'PASTOR' AND es_pastor_principal = TRUE AND activo = TRUE"), sqlite_where=sa.text("rol = 'PASTOR' AND es_pastor_principal = 1 AND activo = 1"))
    op.drop_table('usuarios')
    op.drop_table('iglesias')
    op.drop_table('distritos')
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TYPE rol_usuario")
    # ### end Alembic commands ###
