"""persist refresh sessions

Revision ID: f6117ca1487e
Revises: 3ec9e67695c7
Create Date: 2026-09-27 21:24:36.033111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6117ca1487e'
down_revision: Union[str, Sequence[str], None] = '3ec9e67695c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones_refresh',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('reemplazado_por', sa.Uuid(), nullable=True),
    sa.Column('expira_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reemplazado_por'], ['sesiones_refresh.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesiones_refresh')
    # ### end Alembic commands ###
